/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cundong_utils_PatchUtils */

//#ifndef _Included_com_cundong_utils_PatchUtils
//#define _Included_com_cundong_utils_PatchUtils
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     Java_wu_cy_com_hybirddemo_util_PatchDiffUtil_patch
     *      wu.cy.com.hybirddemo.util.PatchDiffUtil
     * Method:    patch
     * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
     */
    JNIEXPORT jint JNICALL Java_wu_cy_com_hybirddemo_util_PatchDiffUtil_patch
    (JNIEnv *, jobject, jstring, jstring, jstring);

/*
    * Class:    Java_wu_cy_com_hybirddemo_util_PatchDiffUtil_diff
    * Method:    patch
    * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
    */
    JNIEXPORT jint JNICALL Java_wu_cy_com_hybirddemo_util_PatchDiffUtil_diff
        (JNIEnv *, jobject, jstring, jstring, jstring);

    
#ifdef __cplusplus
}
#endif
//#endif
